[project]
name = "fastapi-randomizer"
version = "0.1.0"
requires-python = ">=3.13.8"
dependencies = [
    "alembic>=1.17.2",
    "fastapi[standard]>=0.121.2",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "sqlmodel>=0.0.27",
]
